config/routes.rb
Rails.application.routes.draw do
  get 'creatives/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

  resources :ideas do
    resources :idea_likes
  end

  root to: "ideas#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/idea.rb
class Idea < ApplicationRecord
  mount_uploader :picture, PictureUploader
  belongs_to :user
  has_many :idea_likes, dependent: :destroy
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!  #, only: [:new, :create]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

#TESTING METHODS FOR TINDER LIKE USAGE
  def like_idea
    @idea.idea_likes << IdeaLike.new(params[:idea], liked = true)
    redirect_to ideas_path
  end

  # def dislike_idea
  #   keyword = Keyword.find(params[:keyword_id])
  #   @company.keywords.delete(keyword)
  #   redirect_to company_path
  # end

  # END TESTING METHODS

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)
    @idea.user = current_user

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :short_description, :long_description, :category, :phase, :picture)
    end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= form_with(model: idea, local: true) do |form| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :idea_name %>
  </div>

  <div class="field">
    <%= form.label :short_description %>
    <%= form.text_field :short_description, id: :idea_short_description %>
  </div>

  <div class="field">
    <%= form.label :long_description %>
    <%= form.text_area :long_description, id: :idea_long_description %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :idea_category %>
  </div>

  <div class="field">
    <%= form.label :phase %>
    <%= form.text_field :phase, id: :idea_phase %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :idea_picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ideas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Created_by</th>
      <th>Short description</th>
      <th>Long description</th>
      <th>Category</th>
      <th>Phase</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.user.try(:name) %></td>
        <td><%= idea.short_description %></td>
        <td><%= idea.long_description %></td>
        <td><%= idea.category %></td>
        <td><%= idea.phase %></td>
        <td><%= image_tag idea.picture.card %></td>

        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Short description:</strong>
  <%= @idea.short_description %>
</p>

<p>
  <strong>Long description:</strong>
  <%= @idea.long_description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @idea.category %>
</p>

<p>
  <strong>Phase:</strong>
  <%= @idea.phase %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag @idea.picture.thumb %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

<%= link_to 'LIKE?', new_idea_idea_like_path(@idea) %>