config/routes.rb
Rails.application.routes.draw do
  get 'creatives/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

  resources :ideas do
    resources :idea_likes
  end

  root to: "ideas#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/idea_like.rb
class IdeaLike < ApplicationRecord
  belongs_to :idea
  belongs_to :user
end

app/controllers/idea_likes_controller.rb
class IdeaLikesController < ApplicationController
  before_action :set_idea_like, only: [:show, :edit, :update, :destroy]

  # GET /idea_likes
  # GET /idea_likes.json
  def index
    @idea_likes = IdeaLike.all
  end

  # GET /idea_likes/1
  # GET /idea_likes/1.json
  def show

  end

  # GET /idea_likes/new
  def new
    @idea_like = IdeaLike.new
    # @idea_like.user = current_user
    # @idea_like.idea = idea_like_idea_id
  end

  # GET /idea_likes/1/edit
  def edit
  end

  # POST /idea_likes
  # POST /idea_likes.json
  def create

    @idea_like = IdeaLike.new(idea_like_params)
    @idea_like.user = current_user

    respond_to do |format|
      if @idea_like.save
        format.html { redirect_to @idea_like, notice: 'Idea like was successfully created.' }
        format.json { render :show, status: :created, location: @idea_like }
      else
        format.html { render :new }
        format.json { render json: @idea_like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /idea_likes/1
  # PATCH/PUT /idea_likes/1.json
  def update
    respond_to do |format|
      if @idea_like.update(idea_like_params)
        format.html { redirect_to @idea_like, notice: 'Idea like was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea_like }
      else
        format.html { render :edit }
        format.json { render json: @idea_like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /idea_likes/1
  # DELETE /idea_likes/1.json
  def destroy
    @idea_like.destroy
    respond_to do |format|
      format.html { redirect_to idea_likes_url, notice: 'Idea like was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea_like
      @idea_like = IdeaLike.find(params[:id])


    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_like_params
      params.require(:idea_like).permit(:idea_id, :user_id, :liked)
    end
end

app/helpers/idea_likes_helper.rb
module IdeaLikesHelper
end

app/views/idea_likes/_form.html.erb
<%= form_with(model: idea_like, local: true) do |form| %>
  <% if idea_like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea_like.errors.count, "error") %> prohibited this idea_like from being saved:</h2>

      <ul>
      <% idea_like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :idea_id %>
    <%= form.text_field :idea_id, id: :idea_like_idea_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :idea_like_user_id %>
  </div>

  <div class="field">
    <%= form.label :liked %>
    <%= form.check_box :liked, id: :idea_like_liked %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/idea_likes/edit.html.erb
<h1>Editing Idea Like</h1>

<%= render 'form', idea_like: @idea_like %>

<%= link_to 'Show', @idea_like %> |
<%= link_to 'Back', idea_likes_path %>

app/views/idea_likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Idea Likes</h1>

<table>
  <thead>
    <tr>
      <th>Idea</th>
      <th>User</th>
      <th>Liked</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @idea_likes.each do |idea_like| %>
      <tr>
        <td><%= idea_like.idea.name %></td>
        <td><%= idea_like.user.name %></td>
        <td><%= idea_like.liked %></td>
        <td><%= link_to 'Show', idea_like %></td>
        <td><%= link_to 'Edit', edit_idea_like_path(idea_like) %></td>
        <td><%= link_to 'Destroy', idea_like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea Like', new_idea_like_path %>

app/views/idea_likes/new.html.erb
<h1>New Idea Like</h1>

<%= render 'form', idea_like: @idea_like %>

<%= link_to 'Back', idea_likes_path %>

app/views/idea_likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idea:</strong>
  <%= @idea_like.idea %>
</p>

<p>
  <strong>User:</strong>
  <%= @idea_like.user %>
</p>

<p>
  <strong>Liked:</strong>
  <%= @idea_like.liked %>
</p>

<%= link_to 'Edit', edit_idea_like_path(@idea_like) %> |
<%= link_to 'Back', idea_likes_path %>